-- Migration: Create sessions table (MySQL)
-- Description: Session management table with automatic expiration tracking
-- Compatible with: PlanetScale
-- Date: 2026-01-12

-- Create sessions table
CREATE TABLE IF NOT EXISTS sessions (
  -- Primary key - random session ID generated by application (Oslo)
  id VARCHAR(255) PRIMARY KEY,

  -- Foreign key to users (CHAR(36) to match users.id)
  user_id CHAR(36) NOT NULL,

  -- Session expiration and metadata
  expires_at DATETIME NOT NULL,
  ip_address VARCHAR(45),  -- IPv6 max length
  user_agent TEXT,

  -- Timestamp
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  -- Foreign key constraint
  CONSTRAINT fk_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes for fast lookups
-- Index for finding all sessions for a user
CREATE INDEX idx_sessions_user_id ON sessions(user_id);

-- Index for finding expired sessions (cleanup queries)
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);

-- Composite index for user + expiration queries (finding valid sessions for a user)
CREATE INDEX idx_sessions_user_expires ON sessions(user_id, expires_at);
