-- Migration: Create email_verification_tokens table (MySQL)
-- Description: Email verification tokens for confirming user email addresses
-- Compatible with: PlanetScale
-- Date: 2026-01-12

-- Create email_verification_tokens table
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  -- Primary key - random token generated by application (Oslo)
  token VARCHAR(255) PRIMARY KEY,

  -- Foreign key to users (CHAR(36) to match users.id)
  user_id CHAR(36) NOT NULL,

  -- Email being verified (may differ from current user.email during email change)
  email VARCHAR(255) NOT NULL,

  -- Token expiration
  expires_at DATETIME NOT NULL,

  -- Timestamp
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  -- Foreign key constraint
  CONSTRAINT fk_email_verification_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes for fast lookups
-- Index for finding all verification tokens for a user
CREATE INDEX idx_email_verification_user_id ON email_verification_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX idx_email_verification_expires_at ON email_verification_tokens(expires_at);
