-- Migration: Create password_reset_tokens table (MySQL)
-- Description: Password reset tokens for secure password recovery flow
-- Compatible with: PlanetScale
-- Date: 2026-01-12

-- Create password_reset_tokens table
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  -- Primary key - random token generated by application (Oslo)
  token VARCHAR(255) PRIMARY KEY,

  -- Foreign key to users (CHAR(36) to match users.id)
  user_id CHAR(36) NOT NULL,

  -- Token expiration
  expires_at DATETIME NOT NULL,

  -- Timestamp
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  -- Foreign key constraint
  CONSTRAINT fk_password_reset_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes for fast lookups
-- Index for finding all reset tokens for a user
CREATE INDEX idx_password_reset_user_id ON password_reset_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX idx_password_reset_expires_at ON password_reset_tokens(expires_at);
