-- Migration: Create magic_link_tokens table (MySQL)
-- Description: Magic link tokens for passwordless authentication via email
-- Compatible with: PlanetScale
-- Date: 2026-01-12

-- Create magic_link_tokens table
CREATE TABLE IF NOT EXISTS magic_link_tokens (
  -- Primary key - random token generated by application (Oslo)
  token VARCHAR(255) PRIMARY KEY,

  -- Foreign key to users (CHAR(36) to match users.id)
  user_id CHAR(36) NOT NULL,

  -- Email address for audit/debugging purposes
  email VARCHAR(255) NOT NULL,

  -- Optional redirect URL after successful login
  return_to TEXT,

  -- Token expiration
  expires_at DATETIME NOT NULL,

  -- Timestamp
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  -- Foreign key constraint
  CONSTRAINT fk_magic_link_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create indexes for fast lookups
-- Index for finding all magic link tokens for a user
CREATE INDEX idx_magic_link_user_id ON magic_link_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX idx_magic_link_expires_at ON magic_link_tokens(expires_at);
