-- Migration: Create magic_link_tokens table
-- Description: Magic link tokens for passwordless authentication via email
-- Author: DatabaseArchitect
-- Date: 2026-01-12

-- Create magic_link_tokens table (idempotent)
CREATE TABLE IF NOT EXISTS magic_link_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Email address for audit/debugging purposes
  email TEXT NOT NULL,

  -- Optional redirect URL after successful login
  return_to TEXT,

  -- Token expiration (typically 15 minutes for security)
  expires_at TIMESTAMPTZ NOT NULL,

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all magic link tokens for a user
CREATE INDEX IF NOT EXISTS idx_magic_link_user_id ON magic_link_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_magic_link_expires_at ON magic_link_tokens(expires_at);

-- Comments for documentation
COMMENT ON TABLE magic_link_tokens IS 'Magic link tokens for passwordless authentication via email';
COMMENT ON COLUMN magic_link_tokens.token IS 'Primary key - random magic link token generated by Oslo';
COMMENT ON COLUMN magic_link_tokens.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN magic_link_tokens.email IS 'Email address for audit and debugging purposes';
COMMENT ON COLUMN magic_link_tokens.return_to IS 'Optional URL to redirect to after successful login';
COMMENT ON COLUMN magic_link_tokens.expires_at IS 'Timestamp when token expires - typically 15 minutes for security';
COMMENT ON COLUMN magic_link_tokens.created_at IS 'Timestamp when token was created';

-- Note: Magic link tokens should have short expiration times (15 minutes) for security
-- Tokens are single-use and should be deleted after successful login
-- When a user requests a new magic link, old tokens should be invalidated/deleted
-- Expired tokens should be periodically cleaned up by a background job
-- Magic links automatically verify the user's email address upon successful login
