-- Migration: Create refresh_tokens table
-- Description: Refresh token storage for JWT authentication with revocation support
-- Author: DatabaseArchitect
-- Date: 2026-01-15

-- Create refresh_tokens table (idempotent)
CREATE TABLE IF NOT EXISTS refresh_tokens (
  -- Primary key - UUID generated by database
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Token hash (SHA-256) - stored instead of plaintext for security
  token_hash VARCHAR(64) NOT NULL UNIQUE,

  -- User-friendly name for the token (e.g., "MacBook Pro", "Work Laptop")
  name VARCHAR(255),

  -- Token expiration and revocation
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_used_at TIMESTAMPTZ
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all tokens for a user
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);

-- Index for token hash lookups (for verification)
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

-- Composite index for finding valid (non-revoked, non-expired) tokens for a user
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_valid
  ON refresh_tokens(user_id, expires_at, revoked_at);

-- Comments for documentation
COMMENT ON TABLE refresh_tokens IS 'JWT refresh token storage with revocation support';
COMMENT ON COLUMN refresh_tokens.id IS 'Primary key - UUID for token identification';
COMMENT ON COLUMN refresh_tokens.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'SHA-256 hash of the refresh token - not stored in plaintext';
COMMENT ON COLUMN refresh_tokens.name IS 'User-friendly label for the token (e.g., device name)';
COMMENT ON COLUMN refresh_tokens.expires_at IS 'Timestamp when token expires';
COMMENT ON COLUMN refresh_tokens.revoked_at IS 'Timestamp when token was revoked - NULL if active';
COMMENT ON COLUMN refresh_tokens.created_at IS 'Timestamp when token was created';
COMMENT ON COLUMN refresh_tokens.last_used_at IS 'Timestamp when token was last used for refresh';

-- Note: Refresh token validation checks:
-- 1. Token hash exists in database
-- 2. expires_at > NOW()
-- 3. revoked_at IS NULL
-- Expired and revoked tokens should be periodically cleaned up
