-- Migration: Create devices table
-- Description: Device key storage for phishing-resistant hardware-backed authentication
-- Author: DatabaseArchitect
-- Date: 2026-01-15

-- Create devices table (idempotent)
CREATE TABLE IF NOT EXISTS devices (
  -- Primary key - UUID generated by database
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Unique device identifier (e.g., "dev_web3_abc123")
  device_id VARCHAR(255) NOT NULL UNIQUE,

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Platform type: 'web3' | 'ios' | 'android'
  platform VARCHAR(50) NOT NULL,

  -- Public key (format depends on key_algorithm)
  public_key TEXT NOT NULL,

  -- Wallet address for Web3 only (Ethereum address)
  wallet_address VARCHAR(42),

  -- Key algorithm: 'secp256k1' | 'Ed25519' | 'P-256'
  key_algorithm VARCHAR(50) NOT NULL,

  -- Device status: 'active' | 'revoked'
  status VARCHAR(20) DEFAULT 'active',

  -- Registration timestamp
  registered_at TIMESTAMPTZ NOT NULL,

  -- Last used timestamp (updated on each authenticated request)
  last_used_at TIMESTAMPTZ,

  -- Creation timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all devices for a user
CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);

-- Index for device_id lookups (unique constraint already creates an index)
CREATE INDEX IF NOT EXISTS idx_devices_device_id ON devices(device_id);

-- Index for filtering devices by status
CREATE INDEX IF NOT EXISTS idx_devices_status ON devices(status);

-- Composite index for finding active devices for a user
CREATE INDEX IF NOT EXISTS idx_devices_user_active
  ON devices(user_id, status) WHERE status = 'active';

-- Comments for documentation
COMMENT ON TABLE devices IS 'Hardware-backed device keys for phishing-resistant authentication';
COMMENT ON COLUMN devices.id IS 'Primary key - UUID for device record identification';
COMMENT ON COLUMN devices.device_id IS 'Unique device identifier generated by application';
COMMENT ON COLUMN devices.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN devices.platform IS 'Device platform: web3, ios, or android';
COMMENT ON COLUMN devices.public_key IS 'Cryptographic public key (format depends on key_algorithm)';
COMMENT ON COLUMN devices.wallet_address IS 'Ethereum wallet address (Web3 only)';
COMMENT ON COLUMN devices.key_algorithm IS 'Signature algorithm: secp256k1, Ed25519, or P-256';
COMMENT ON COLUMN devices.status IS 'Device status: active or revoked';
COMMENT ON COLUMN devices.registered_at IS 'Timestamp when device was registered';
COMMENT ON COLUMN devices.last_used_at IS 'Timestamp when device was last used for authentication';
COMMENT ON COLUMN devices.created_at IS 'Timestamp when device record was created';

-- Note: Device validation checks:
-- 1. device_id exists in database
-- 2. status = 'active'
-- 3. Signature verified with public_key
-- Revoked devices should remain in database for audit trail
