-- Migration: Create sessions table (SQLite)
-- Description: Session management table with automatic expiration tracking
-- Compatible with: Turso, Cloudflare D1
-- Date: 2026-01-12

-- Create sessions table
CREATE TABLE IF NOT EXISTS sessions (
  -- Primary key - random session ID generated by application (Oslo)
  id TEXT PRIMARY KEY,

  -- Foreign key to users (TEXT in SQLite since user.id is TEXT)
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Session expiration and metadata
  expires_at INTEGER NOT NULL,  -- Unix timestamp
  ip_address TEXT,
  user_agent TEXT,

  -- Timestamp
  created_at INTEGER DEFAULT (unixepoch())
);

-- Create indexes for fast lookups
-- Index for finding all sessions for a user
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

-- Index for finding expired sessions (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

-- Composite index for user + expiration queries (finding valid sessions for a user)
CREATE INDEX IF NOT EXISTS idx_sessions_user_expires ON sessions(user_id, expires_at);
