-- Migration: Create email_verification_tokens table (SQLite)
-- Description: Email verification tokens for confirming user email addresses
-- Compatible with: Turso, Cloudflare D1
-- Date: 2026-01-12

-- Create email_verification_tokens table
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users (TEXT in SQLite since user.id is TEXT)
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Email being verified (may differ from current user.email during email change)
  email TEXT NOT NULL,

  -- Token expiration (Unix timestamp)
  expires_at INTEGER NOT NULL,

  -- Timestamp
  created_at INTEGER DEFAULT (unixepoch())
);

-- Create indexes for fast lookups
-- Index for finding all verification tokens for a user
CREATE INDEX IF NOT EXISTS idx_email_verification_user_id ON email_verification_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_email_verification_expires_at ON email_verification_tokens(expires_at);
