-- Migration: Create password_reset_tokens table (SQLite)
-- Description: Password reset tokens for secure password recovery flow
-- Compatible with: Turso, Cloudflare D1
-- Date: 2026-01-12

-- Create password_reset_tokens table
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users (TEXT in SQLite since user.id is TEXT)
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Token expiration (Unix timestamp)
  expires_at INTEGER NOT NULL,

  -- Timestamp
  created_at INTEGER DEFAULT (unixepoch())
);

-- Create indexes for fast lookups
-- Index for finding all reset tokens for a user
CREATE INDEX IF NOT EXISTS idx_password_reset_user_id ON password_reset_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_password_reset_expires_at ON password_reset_tokens(expires_at);
