-- Migration: Create magic_link_tokens table (SQLite)
-- Description: Magic link tokens for passwordless authentication via email
-- Compatible with: Turso, Cloudflare D1
-- Date: 2026-01-12

-- Create magic_link_tokens table
CREATE TABLE IF NOT EXISTS magic_link_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users (TEXT in SQLite since user.id is TEXT)
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Email address for audit/debugging purposes
  email TEXT NOT NULL,

  -- Optional redirect URL after successful login
  return_to TEXT,

  -- Token expiration (Unix timestamp)
  expires_at INTEGER NOT NULL,

  -- Timestamp
  created_at INTEGER DEFAULT (unixepoch())
);

-- Create indexes for fast lookups
-- Index for finding all magic link tokens for a user
CREATE INDEX IF NOT EXISTS idx_magic_link_user_id ON magic_link_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_magic_link_expires_at ON magic_link_tokens(expires_at);
